[x86][mod]: optimize lstm op
openppl-public/ppl.nn pull request #685
Opened 2022-09-05 12:35 UTC by czHappy

- [x] support packed weights when W and R are constants.
- [ ] block optimization when batch is small.

2022-09-05 12:45 UTC, czHappy commented on src/ppl/nn/engines/x86/impls/include/ppl/kernel/x86/fp32/lstm.h
> +    const float **X_weight,
这里改成了二级指针的方式，X_weight[nd]表示第nd个direction的W矩阵的权重；has_packed_w = true时， X_weight是packed后的权重，has_packed_w = false时，X_weight是原始权重

2022-09-05 12:49 UTC, czHappy commented on src/ppl/nn/engines/x86/optimizer/ops/onnx/lstm_op.cc
> +    if (w_data != nullptr) {
这里根据输入tensor W (node->GetInput(1))是否为constant来决定是否对其进行pack, 如果需要pack则param_->packed_w存储的是W pack后的权重，否则存储的是W的首地址。

2022-09-05 12:50 UTC, czHappy commented on src/ppl/nn/params/onnx/lstm_param.h
> +    bool has_packed_r;
packed_w[2]表示两个方向上W权重，是否经过了pack由has_packed_w指示。packed_r[2]同理。

2022-09-09 06:47 UTC, Alcanderian requested changes
代码有不少问题需要修改

2022-09-09 06:47 UTC, Alcanderian commented on src/ppl/nn/engines/x86/kernels/onnx/lstm_kernel.cc
> +        if(param_->has_packed_w) ppl::common::AlignedFree(param_->packed_w[i]);
为何在这里free？为何要用到num_direction？用nullptr初始化的意图是？

2022-09-09 06:47 UTC, Alcanderian commented on src/ppl/nn/engines/x86/optimizer/ops/onnx/lstm_op.cc
> +    aux_param_.param = param_.get();
检查完参数再赋值

2022-09-09 06:47 UTC, Alcanderian commented on src/ppl/nn/engines/x86/optimizer/ops/onnx/lstm_op.cc
> +    } else {
这个else合理吗？w_data == nullptr

2022-09-09 06:47 UTC, Alcanderian commented on src/ppl/nn/engines/x86/params/lstm_param.h
> +    bool has_packed_w;
其实我觉得这两个不需要在这里存，根据packed_w和packed_r是否为null就能判断

2022-09-09 06:47 UTC, Alcanderian commented on src/ppl/nn/params/onnx/lstm_param.h
> -
这个文件要还原成原来的样子，不要产生莫名的blame

2022-09-09 07:17 UTC, czHappy commented on src/ppl/nn/engines/x86/optimizer/ops/onnx/lstm_op.cc
> +    } else {
> 这个else合理吗？w_data == nullptr

w_data_it = graph_data->constants.find(node->GetInput(1)) ; 
w_data = (const float*)w_data_it->second.data.GetData() ; 如果w_data为空说明不是constant的，就不需要pack了，packed_w指针直接指向原始的weight

2022-09-23 06:53 UTC, merged